poodtam/web/views/accounts.py
import datetime
import markdown
import mongoengine as me

from flask import (
    Blueprint,
    render_template,
    url_for,
    redirect,
    request,
    session,
    current_app,
    send_file,
    abort,
    flash,
)
from flask_login import login_user, logout_user, login_required, current_user

from .. import models
from .. import oauth
from .. import acl
from .. import forms

module = Blueprint("accounts", __name__)


@module.route("/login", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        return redirect(url_for("dashboard.index"))

    form = forms.accounts.LoginForm()
    if form.validate_on_submit():
        username = form.username.data
        user = models.User.objects(username=username).first()
        if user and oauth.handle_authorized_user(form):
            return redirect(url_for("dashboard.index"))
        flash('Incorrect username or password.')
    return render_template("accounts/login.html", form=form)


@module.route("/logout")
@login_required
def logout():
    logout_user()
    session.clear()

    return redirect(url_for("dashboard.index"))

@module.route("/register", methods=["GET", "POST"])
def register():
    form = forms.accounts.RegistrationForm()
    if not form.validate_on_submit():
        return render_template("accounts/register.html", form=form)

    if oauth.create_user(form):
        return redirect(url_for("accounts.login"))
    
    flash("Username already exists")
    return render_template("accounts/register.html", form=form)


@module.route("/edit-profile", methods=["GET", "POST"])
@login_required
def edit():
    user = current_user._get_current_object()
    chats = models.Chat.objects(user=user).order_by("-created_date")
    chat = chats.first()
    form = forms.accounts.ProfileForm(obj=user)
    if not form.validate_on_submit():
        return render_template("accounts/edit.html", chats=chats, chat=chat, form=form)

    user = current_user._get_current_object()
    form.populate_obj(user)
    if form.pic.data:
        print(form.pic.data)
        if user.picture:
            user.picture.replace(
                form.pic.data,
                filename=form.pic.data.filename,
                content_type=form.pic.data.content_type,
            )
        else:
            user.picture.put(
                form.pic.data,
                filename=form.pic.data.filename,
                content_type=form.pic.data.content_type,
            )


    user.save()
    flash("Saved Successfully!")
    return render_template("accounts/edit.html", chats=chats, chat=chat, form=form)

@module.route("/accounts/<user_id>/picture/<filename>", methods=["GET", "POST"])
def picture(user_id, filename):
    user = models.User.objects.get(id=user_id)

    if not user or not user.picture or user.picture.filename != filename:
        return abort(403)

    response = send_file(
        user.picture,
        download_name=user.picture.filename,
        mimetype=user.picture.content_type,
    )
    return response



@module.route("/new_chat")
@login_required
def new_chat():
    chat = models.Chat()
    chat.user = current_user._get_current_object()
    chat.name = f"Chat {models.Chat.objects().count() + 1}"
    chat.create_bot_message("text", "Ask me...")
    chat.save()

    return redirect(url_for("dashboard.index", chat_id=chat.id))


@module.route("/chats/<chat_id>/delete")
@login_required
def delete_chat(chat_id):
    chat = models.Chat.objects.get(id=chat_id)
    chat.delete()

    return redirect(url_for("dashboard.index"))

poodtam/web/views/dashboard.py
from flask import Blueprint, render_template, request, redirect, url_for
from flask_login import current_user, login_required

from poodtam import models
from chatbot import chat_answer
from chatbot import TYPE_CORPUS as RESTAURANT_TYPE
from chatbot.dataset import EXAMPLE_SENTENCE

import random
import datetime
import time
import pandas as pd
import io

module = Blueprint("dashboard", __name__, url_prefix="/")


def is_openning(opened_time, closed_time):
    now_time = datetime.datetime.now().time()
    if now_time > opened_time.time() and now_time < closed_time.time():
        return True
    return False

@module.route("/", methods=["GET"])
@login_required
def index():
    user = current_user._get_current_object()
    chats = models.Chat.objects(user=user).order_by("-created_date")

    chat_id = request.args.get("chat_id", None)
    chat = models.Chat.objects(user=user).first()
    if chat_id:
        chat = models.Chat.objects.get(id=chat_id)
        
    if not chat:
        chat = models.Chat()
        chat.user = user
        chat.name = f"Chat {models.Chat.objects().count() + 1}"
        chat.create_bot_message("text", "Ask me...")
        chat.save()
    return render_template(
        "/dashboard/index.html",
        chat=chat,
        chats=chats,
        is_openning=is_openning,
        RESTAURANT_TYPE=RESTAURANT_TYPE,
    )

@module.route("/submit_message/<chat_id>", methods=["GET"])
def submit_message(chat_id):
    chat = models.Chat.objects.get(id=chat_id)
    input = request.args.get("input", None)
    if input:
        chat.create_user_message("text", input)
        chat_answer(chat, input)
    return redirect(url_for('dashboard.index', chat_id=chat.id))

@module.route("/random_sentence")
def random_sentence():
    sentence = random.choice(EXAMPLE_SENTENCE)
    return sentence

poodtam/web/templates/dashboard/index.html
{% extends "/base/default-page.html" %}
{% import "/components/message.html" as message_renderer %}
{% import "/components/quick-reply.html" as quick_reply %}

{% block title %}
 Poodtam | {{ chat.name }}
{% endblock %}

{% block content %}
  <div class="ui raised padded secondary segment">
    <span class="ui black text" style="font-weight: 700;">{{ chat.name }}</span>
    <a style="margin-left: 1em; cursor: pointer" href="{{ url_for('accounts.delete_chat', chat_id=chat.id) }}">
      <i class="small red trash icon"></i>
    </a>
  </div>
  <div class="ui raised padded secondary fitted segment">
    <div class="ui hidden divider"></div>
    <div class="ui basic segment">
      <div class="ui feed">
        {% for message in chat.messages %}
          {% if message.sender == "bot" %}
            {{ message_renderer.BotMessage(message, current_user, is_openning) }}
          {% else %}
            {{ message_renderer.UserMessage(message, current_user) }}
          {% endif %}
        {% endfor %}
      </div>
    </div>
    <div class="ui top attached right aligned segment">
      {{ quick_reply.Reset(chat) }} Current Given Information:&ensp;
      <div class="ui {{ 'brown' if chat.current_type }} label">
        {{ chat.current_type.title() if chat.current_type else 'Not Selected' }}
        <div class="detail">Type</div>
      </div>
      <div class="ui {{ 'green' if chat.current_price }} label">
        {{ chat.current_price.title() if chat.current_price else 'Not Selected' }}
        <div class="detail">Price</div>
      </div>
      <div class="ui {{ 'purple' if chat.current_time }} label">
        {% if chat.current_time %}
          {% if chat.current_time.lower() == "specific" and chat.selected_time %}
            {{ chat.selected_time.strftime("%H:%M") }}
          {% else %}
            {{ chat.current_time.title() }}
          {% endif %}
        {% else %}
          Not Selected
        {% endif %}
        <div class="detail">Time</div>
      </div>
    </div>
    <div class="ui fluid attached segment">
      {% if chat.current_state == 'price' %}
        {{ quick_reply.Price(chat) }}
      {% elif chat.current_state == 'time' %}
        {{ quick_reply.Time(chat) }}
      {% else %}
        {{ quick_reply.Recommandation(chat) }}
        <div class="ui dropdown pointing scrolling" id="list-type">
          <a class="ui primary icon circular label basic" 
            style="cursor: pointer !important"
            onmouseover="this.style = 'background-color: #2185D0; color: white'; " 
            onmouseleave="this.style = 'background-color: none; color: #2185D0'; ">
            <p><b>Select Type</b> &ensp; <i class="list-type list icon"></i></p>
            <!-- List restaurants by selected type  -->
          </a>
          <div class="menu">
            <div class="header">
              List Restaurant by Type
            </div>
            <div class="ui icon search input">
              <i class="search icon"></i>
              <input type="text" placeholder="Search restaurant type...">
            </div>
            {% for type in RESTAURANT_TYPE %}
              <a class="item" onclick="input = $('#input')[0]; input.value += '{{ type }} '; input.focus()">{{ type }}</a>
            {% endfor %}
          </div>
        </div>
        &ensp;

        <div class="ui dropdown bottom pointing" id="list-price">
          <a class="ui primary icon circular label basic" 
            style="cursor: pointer !important"
            onmouseover="this.style = 'background-color: #2185D0; color: white'; " 
            onmouseleave="this.style = 'background-color: none; color: #2185D0'; ">
            <p><b>Select Price</b> &ensp; <i class="list-price list icon"></i></p>
            <!-- List prices range for restaurants  -->
          </a>
          <div class="menu">
              <a class="item" onclick="input = $('#input')[0]; input.value += 'Low Price '; input.focus()">Low Price</a>
              <a class="item" onclick="input = $('#input')[0]; input.value += 'Medium Price '; input.focus()">Medium Price</a>
              <a class="item" onclick="input = $('#input')[0]; input.value += 'High Price '; input.focus()">High Price</a>
              <a class="item" onclick="input = $('#input')[0]; input.value += 'Anyprice '; input.focus()">Anyprice</a>
          </div>
        </div>
        &ensp;

        <div class="ui dropdown bottom pointing" id="list-time">
          <a class="ui primary icon circular label basic" 
            style="cursor: pointer !important"
            onmouseover="this.style = 'background-color: #2185D0; color: white'; " 
            onmouseleave="this.style = 'background-color: none; color: #2185D0'; ">
            <p><b>Select Time</b> &ensp; <i class="list-time list icon"></i></p>
            <!-- List time that you want to go -->
          </a>
          <div class="menu">
            <a class="item" onclick="input = $('#input')[0]; input.value += 'Now '; input.focus()">Now</a>
            <a class="item" onclick="input = $('#input')[0]; input.value += 'Breakfast '; input.focus()">Breakfast</a>
            <a class="item" onclick="input = $('#input')[0]; input.value += 'Lunch '; input.focus()">Lunch</a>
            <a class="item" onclick="input = $('#input')[0]; input.value += 'Dinner '; input.focus()">Dinner</a>
            <a class="item" onclick="input = $('#input')[0]; input.value += 'Specific Time '; input.focus()">Specific Time</a>
            <a class="item" onclick="input = $('#input')[0]; input.value += 'Anytime '; input.focus()">Anytime</a>
          </div>
        </div>
        &ensp;

        {{ quick_reply.Random() }}
      {% endif %}
      
      <!-- INPUT START -->
      <div class="ui blue message center floating aligned">
        <form method="GET" action="{{ url_for('dashboard.submit_message', chat_id=chat.id) }}">
          <div class="ui fluid transparent input">
            <input type="text" name="input" id="input" placeholder="Ask me about Hatyai restaurant...">
            <button class="ui primary icon button">
              Submit
              <i class="send icon"></i>
            </button>
          </div>
        </form>
      </div>
      
      <!-- END INPUT -->
    </div>
  </div>    
  {% include "/components/back-to-top.html" %}
{% endblock %}

{% block additional_js %}
  <script>
    window.top.location.href = "#input"
    $('.ui.dropdown').dropdown()
  </script>
  {% if chat.messages | length > 2 %}
    <script>
      // <!-- MOCK LOADING BOT RESPONSE MESSAGE -->
      bot_response = document.getElementById("{{ chat.messages[-1].uid }}").style.display = "none";
      setTimeout(function() {
        bot_response = document.getElementById("{{ chat.messages[-1].uid }}");
        bot_response.style.display = "none";
        $(bot_response).transition('fade up');
        window.scrollTo(0, ScreenHeight);
      },200);
    </script>
  {% endif %}
{% endblock %}