poodtam/web/views/accounts.py
import datetime
import markdown
import mongoengine as me

from flask import (
    Blueprint,
    render_template,
    url_for,
    redirect,
    request,
    session,
    current_app,
    send_file,
    abort,
    flash,
)
from flask_login import login_user, logout_user, login_required, current_user

from .. import models
from .. import oauth
from .. import acl
from .. import forms

module = Blueprint("accounts", __name__)


@module.route("/login", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        return redirect(url_for("dashboard.index"))

    form = forms.accounts.LoginForm()
    if form.validate_on_submit():
        username = form.username.data
        user = models.User.objects(username=username).first()
        if user and oauth.handle_authorized_user(form):
            return redirect(url_for("dashboard.index"))
        flash('Incorrect username or password.')
    return render_template("accounts/login.html", form=form)


@module.route("/logout")
@login_required
def logout():
    logout_user()
    session.clear()

    return redirect(url_for("dashboard.index"))

@module.route("/register", methods=["GET", "POST"])
def register():
    form = forms.accounts.RegistrationForm()
    if not form.validate_on_submit():
        return render_template("accounts/register.html", form=form)

    if oauth.create_user(form):
        return redirect(url_for("accounts.login"))
    
    flash("Username already exists")
    return render_template("accounts/register.html", form=form)


@module.route("/edit-profile", methods=["GET", "POST"])
@login_required
def edit():
    user = current_user._get_current_object()
    chats = models.Chat.objects(user=user).order_by("-created_date")
    chat = chats.first()
    form = forms.accounts.ProfileForm(obj=user)
    if not form.validate_on_submit():
        return render_template("accounts/edit.html", chats=chats, chat=chat, form=form)

    user = current_user._get_current_object()
    form.populate_obj(user)
    if form.pic.data:
        print(form.pic.data)
        if user.picture:
            user.picture.replace(
                form.pic.data,
                filename=form.pic.data.filename,
                content_type=form.pic.data.content_type,
            )
        else:
            user.picture.put(
                form.pic.data,
                filename=form.pic.data.filename,
                content_type=form.pic.data.content_type,
            )


    user.save()
    flash("Saved Successfully!")
    return render_template("accounts/edit.html", chats=chats, chat=chat, form=form)

@module.route("/accounts/<user_id>/picture/<filename>", methods=["GET", "POST"])
def picture(user_id, filename):
    user = models.User.objects.get(id=user_id)

    if not user or not user.picture or user.picture.filename != filename:
        return abort(403)

    response = send_file(
        user.picture,
        download_name=user.picture.filename,
        mimetype=user.picture.content_type,
    )
    return response



@module.route("/new_chat")
@login_required
def new_chat():
    chat = models.Chat()
    chat.user = current_user._get_current_object()
    chat.name = f"Chat {models.Chat.objects().count() + 1}"
    chat.create_bot_message("text", "Ask me...")
    chat.save()

    return redirect(url_for("dashboard.index", chat_id=chat.id))


@module.route("/chats/<chat_id>/delete")
@login_required
def delete_chat(chat_id):
    chat = models.Chat.objects.get(id=chat_id)
    chat.delete()

    return redirect(url_for("dashboard.index"))

poodtam/web/views/dashboard.py
from flask import Blueprint, render_template, request, redirect, url_for
from flask_login import current_user, login_required

from poodtam import models
from chatbot import chat_answer
from chatbot import TYPE_CORPUS as RESTAURANT_TYPE
from chatbot.dataset import EXAMPLE_SENTENCE

import random
import datetime
import time
import pandas as pd
import io

module = Blueprint("dashboard", __name__, url_prefix="/")


def is_openning(opened_time, closed_time):
    now_time = datetime.datetime.now().time()
    if now_time > opened_time.time() and now_time < closed_time.time():
        return True
    return False

@module.route("/", methods=["GET"])
@login_required
def index():
    user = current_user._get_current_object()
    chats = models.Chat.objects(user=user).order_by("-created_date")

    chat_id = request.args.get("chat_id", None)
    chat = models.Chat.objects(user=user).first()
    if chat_id:
        chat = models.Chat.objects.get(id=chat_id)
        
    if not chat:
        chat = models.Chat()
        chat.user = user
        chat.name = f"Chat {models.Chat.objects().count() + 1}"
        chat.create_bot_message("text", "Ask me...")
        chat.save()
    return render_template(
        "/dashboard/index.html",
        chat=chat,
        chats=chats,
        is_openning=is_openning,
        RESTAURANT_TYPE=RESTAURANT_TYPE,
    )

@module.route("/submit_message/<chat_id>", methods=["GET"])
def submit_message(chat_id):
    chat = models.Chat.objects.get(id=chat_id)
    input = request.args.get("input", None)
    if input:
        chat.create_user_message("text", input)
        chat_answer(chat, input)
    return redirect(url_for('dashboard.index', chat_id=chat.id))

@module.route("/random_sentence")
def random_sentence():
    sentence = random.choice(EXAMPLE_SENTENCE)
    return sentence

poodtam/web/templates/components/back-to-top.html
<button onclick="scrollToTop()" id="scroll-to-top" title="Go to top page" class="ui icon black button">
  <i class="angle double up icon"></i>&ensp; Back to Top
</button>

<button onclick="scrollToBottom()" id="scroll-to-bottom" title="Go to bottom page" class="ui icon black button">
  <i class="angle double down icon"></i>&ensp; Scroll Down
</button>

<style>
#scroll-to-top {
  display: none; /* Hidden by default */
  position: fixed; /* Fixed/sticky position */
  bottom: 10px; /* Place the button at the bottom of the page */
  right: 35px; /* Place the button 30px from the right */
  z-index: 99; /* Make sure it does not overlap */
}
#scroll-to-bottom {
  display: none; /* Hidden by default */
  position: fixed; /* Fixed/sticky position */
  bottom: 10px; /* Place the button at the bottom of the page */
  right: 35px; /* Place the button 30px from the right */
  z-index: 99; /* Make sure it does not overlap */
}
</style>

<script>
window.onload = window.scrollTo(0, document.body.scrollHeight);
let BackToTopButton = document.getElementById("scroll-to-top");
let BackToBottomButton = document.getElementById("scroll-to-bottom");
let ScreenHeight = document.body.scrollHeight;
window.onscroll = function() {
  if (document.body.scrollTop > ScreenHeight / 2 || document.documentElement.scrollTop > ScreenHeight / 2) {
    if (BackToTopButton.style.display == "none") {
      $(BackToTopButton).transition("fade up");
      $(BackToBottomButton).transition("fade up");
    } 
    BackToTopButton.style.display = "block";
    BackToBottomButton.style.display = "none";
  } else {
    if (BackToBottomButton.style.display == "none") {
      $(BackToBottomButton).transition("fade up");
      $(BackToTopButton).transition("fade up");
    } 
    BackToBottomButton.style.display = "block";
    BackToTopButton.style.display = "none";
  } 
};
function scrollToTop() {
  document.getElementById("html").style.scrollBehavior = "smooth";
  window.scrollTo(1, 0);
  document.getElementById("html").style.scrollBehavior = "";
}
function scrollToBottom() {
  document.getElementById("html").style.scrollBehavior = "smooth";
  window.scrollTo(0, ScreenHeight);
  document.getElementById("html").style.scrollBehavior = "";
}
</script>

poodtam/web/templates/components/menu-bar.html
<div class="ui left fixed vertical inverted menu" style="box-sizing: border-box; width: 18.75%">
  {% if current_user.is_authenticated %}
    <div class="item">
      <div class="ui inverted icon header center aligned" style="padding-top: 1em;">
        {% if current_user.get_picture() %}
          <img class="ui massive avatar image" src="{{ current_user.get_picture() }}" style="margin-bottom: 0.7em;"><br>
        {% else %}
          <i class="inverted large teal circular colored user icon"></i>
        {% endif %}
        {{ current_user.name }}
      </div>
    </div>
  <a class="{{ 'active' if 'profile' in request.url }} item" href="{{ url_for('accounts.edit') }}">
    <i class="edit icon"></i>Profile
    </a>
    <a class="item" href="{{ url_for('accounts.new_chat') }}">
        <i class="plus square outline icon"></i>New Chat
    </a>
  <div class="item">
    <div class="header">Chat</div>
    <div class="menu">
      {% for chat_i in chats %}
      <a class="{{ 'active' if chat_i.id == chat.id }} item" href="{{ url_for('dashboard.index', chat_id=chat_i.id) }}">
          <i class="square {{ 'full' if chat_i.id == chat.id else 'outline' }} icon"></i>
          {{ chat_i.name }}
      </a>
      {% endfor %}
    </div>
  </div>
  <a class="item" href="{{ url_for('accounts.logout') }}">
    <i class="inverted red sign out icon"></i><span class="ui inverted red text">Logout</span>
  </a>
  {% else %}
  <div class="item"><div class="header">Poodtam Dasboard</div></div>
  <a class="{{ 'active' if 'login' in request.url }} item" href="{{ url_for('accounts.login') }}">Login</a>
  <a class="{{ 'active' if 'register' in request.url }} item" href="{{ url_for('accounts.register') }}">Sign up</a>
  {% endif %}
</div>

<script>
  $('ui.dropdown').dropdown();
</script>

poodtam/web/templates/components/message.html
{% macro UserMessage(message, current_user) %}
<div class="event" id="{{ message.uid }}">
    <div class="label">
      {% if current_user.get_picture() %}
        <img class="ui big avatar image" src="{{ current_user.get_picture() }}">
      {% else %}
        <i class="big circular colored teal inverted user icon"></i>
      {% endif %}
    </div>
    <div class="content">
      <div class="summary">
        <span class="ui teal text">
          {{ current_user.name }}
        </span>
        <div class="date">
          {{ message.created_date.strftime("%d %b %y %H:%M") }}
        </div>
      </div>
      <div class="ui fitted compact basic raised segment">
        <div class="ui basic huge label">
          <div class="ui basic left aligned segment">
            {{ message.text }}
          </div>
        </div>
      </div>
    </div>
  </div>
{% endmacro %}

{% macro BotMessage(message, current_user, is_openning) %}
<div class="event" id="{{ message.uid }}">
    <div class="label">
      <i class="big circular colored orange inverted cat icon"></i>
    </div>
    <div class="content">
      <div class="summary">
        <span class="ui orange text">
          Poodtam
        </span>
        <div class="date">
          {{ message.created_date.strftime("%d %b %y %H:%M") }}
        </div>
      </div>
      <div class="ui fitted compact basic raised segment">
        <div class="ui basic huge label">
          {% if message.type == "text" %}
            <div class="ui basic left aligned segment">
              {{ message.text | replace('\n', '<br>') | safe}}
            </div>
          {% elif message.type == 'dataframe' %}
            <div class="ui basic segment left aligned">
              {% if not message.get_dataframe().empty %}
                {% for row, data in message.get_dataframe().iterrows() %}
                  <div class="ui message">
                    <p>
                      <h3 class="ui header" style="margin-bottom: 0.5em;">{{ data['name'] }}</h3>
                      {% for type in data['type'].split(",") %}
                        {% if type in current_user.preferred_types %}
                          <div class="ui teal label link pop" style="cursor: default;" data-content="You liked this type" data-variation="inverted tiny" data-position="bottom center">
                            {{ type }}
                          </div>
                        {% endif %}
                      {% endfor %}
                      {% for type in data['type'].split(",") %}
                        {% if type not in current_user.preferred_types %}
                          <div class="ui grey label" style="cursor: default;">
                            {{ type }}
                          </div>
                        {% endif %}
                      {% endfor %}
                    </p>
                    <div class="item" style="font-weight: 500">
                      Opening Time
                      {{ data['opening time'].strftime("%H:%M") }} - {{ data['closing time'].strftime("%H:%M") }}
                      |
                      {% if data['closed on'] == "No" %}
                        Everyday
                      {% else %}
                        Closed on {{ data["closed on"] }}
                      {% endif%}
                      {% if is_openning(data['opening time'], data['closing time']) %}
                      <div class="ui basic green left pointing label">Now opened</div>
                        {% else %}
                      <div class="ui basic red left pointing label">Now Closed</div>
                      {% endif %}
                    </div>
                    <p>
                      <div class="item" style="font-weight: 500">
                        Price range
                        {% if data["price"] == "฿" %}
                        Less than 100 Baht&ensp;<div class="ui basic {{ 'teal link pop' if data['price'] in current_user.preferred_prices else 'grey' }} label tag" data-content="You liked this price" data-variation="inverted tiny" data-position="bottom center" style="font-weight: 600 !important;">฿</div>
                        {% elif data["price"] == "฿฿" %}
                        100 Baht - 250 Baht&ensp;<div class="ui basic {{ 'teal link pop' if data['price'] in current_user.preferred_prices else 'grey' }} label tag" data-content="You liked this price" data-variation="inverted tiny" data-position="bottom center" style="font-weight: 600 !important;">฿฿</div>
                        {% else %}
                        More than 250 Baht&ensp;<div class="ui basic {{ 'teal link pop' if data['price'] in current_user.preferred_prices else 'grey' }} label tag" data-content="You liked this price" data-variation="inverted tiny" data-position="bottom center" style="font-weight: 600 !important;">฿฿฿</div>
                        {% endif %}
                      </div> 
                    </p>
                    <p>
                      <div class="item"><a><i class="phone alternate icon"></i> {{ '0' if data["phone"][0] | string not in ["0", "-"] }}{{ data["phone"] | string }}</a></div>
                      <div class="item"><a href="{{ data['address'] }}" target="_blank" ><i class="map marker alternate icon"></i>View on Google Maps</a></div>
                    </p>
                  </div>
                {% endfor %}
              {% else %}
                > DataFrame is Empty
              {% endif %}
            </div>
          {% endif %}
        </div>
      </div>
    </div>
  </div>

  <script>
    $('.link.pop').popup({
      delay: {
      show: 500,
    }});
  </script>
{% endmacro %}

poodtam/web/templates/components/navbar.html
<div class="ui fluid aligned inverted basic fitted right aligned segment" style="padding: 3px;">
  <div class="ui inverted fixed menu">
    <div class="right menu">
      <a class="item"  href="{{ url_for('dashboard.index') }}">
        <i class="cat icon"></i>&ensp;<b>Poodtam Chatbot</b>
      </a>
    </div>
  </div>
</div>

<script>
  $('.ui.dropdown')
    .dropdown()
  ;
</script>

poodtam/web/templates/components/quick-reply.html
{% macro Recommandation(chat) %}
  <!-- Quick Reply #List By Preferred -->
  <a class="ui primary icon circular label basic" 
    style="cursor: pointer !important"
    onmouseover="this.style = 'background-color: #2185D0; color: white'; " 
    onmouseleave="this.style = 'background-color: none; color: #2185D0'; "
    href="{{ url_for('dashboard.submit_message', chat_id=chat.id, input='Recommand restaurant for me') }}">
    <p><b>Recommand restaurant for me</b> &ensp; <i class="recommand send icon" ></i></p>
    <!-- List preferred restaurants currently open -->
  </a>
  &ensp;
  <!-- Quick Reply #List By Type -->
{% endmacro %}

{% macro Price(chat) %}
  <a class="ui primary icon circular label basic" 
    style="cursor: pointer !important"
    onmouseover="this.style = 'background-color: #2185D0; color: white'; " 
    onmouseleave="this.style = 'background-color: none; color: #2185D0'; "
    href="{{ url_for('dashboard.submit_message', chat_id=chat.id, input='Low') }}">
    <p><b>1. Low</b> &ensp; <i class="low send icon" ></i></p>
      <!-- Less than 100 baht -->
  </a>
  &ensp;
    <a class="ui primary icon circular label basic" 
      style="cursor: pointer !important"
    onmouseover="this.style = 'background-color: #2185D0; color: white'; " 
    onmouseleave="this.style = 'background-color: none; color: #2185D0'; "
    href="{{ url_for('dashboard.submit_message', chat_id=chat.id, input='Medium') }}">
    <p><b>2. Medium</b> &ensp; <i class="med send icon" ></i></p>
    <!-- 100 baht - 250 baht -->
  </a>
  &ensp;
  <a class="ui primary icon circular label basic" 
    style="cursor: pointer !important"
    onmouseover="this.style = 'background-color: #2185D0; color: white'; " 
    onmouseleave="this.style = 'background-color: none; color: #2185D0'; "
    href="{{ url_for('dashboard.submit_message', chat_id=chat.id, input='High') }}">
    <p><b>3. High</b> &ensp; <i class="high send icon" ></i></p>
      <!-- Less than 100 baht -->
  </a>
  &ensp;
  <a class="ui primary icon circular label basic" 
    style="cursor: pointer !important"
    onmouseover="this.style = 'background-color: #2185D0; color: white'; " 
    onmouseleave="this.style = 'background-color: none; color: #2185D0'; "
    href="{{ url_for('dashboard.submit_message', chat_id=chat.id, input='Anyprice') }}">
    <p><b>4. Any Price</b> &ensp; <i class="anyprice send icon" ></i></p>
      <!-- Show all price of restaurants -->
  </a>
  &ensp;
{% endmacro %}


{% macro Time(chat) %}
  <a class="ui primary icon circular label basic" 
    style="cursor: pointer !important"
    onmouseover="this.style = 'background-color: #2185D0; color: white'; " 
    onmouseleave="this.style = 'background-color: none; color: #2185D0'; "
    href="{{ url_for('dashboard.submit_message', chat_id=chat.id, input='Now') }}">
    <p><b>1. Now</b> &ensp; <i class="Now send icon" ></i></p>
      <!-- All openning time -->
  </a>
  &ensp;
  <a class="ui primary icon circular label basic" 
    style="cursor: pointer !important"
    onmouseover="this.style = 'background-color: #2185D0; color: white'; " 
    onmouseleave="this.style = 'background-color: none; color: #2185D0'; "
    href="{{ url_for('dashboard.submit_message', chat_id=chat.id, input='Breakfast') }}">
    <p><b>2. Breakfast</b> &ensp; <i class="Breakfast send icon" ></i></p>
      <!-- All openning time -->
  </a>
  &ensp;
  <a class="ui primary icon circular label basic" 
    style="cursor: pointer !important"
    onmouseover="this.style = 'background-color: #2185D0; color: white'; " 
    onmouseleave="this.style = 'background-color: none; color: #2185D0'; "
    href="{{ url_for('dashboard.submit_message', chat_id=chat.id, input='Lunch') }}">
    <p><b>3. Lunch</b> &ensp; <i class="Lunch send icon" ></i></p>
      <!-- All openning time -->
  </a>
  &ensp;
  <a class="ui primary icon circular label basic" 
    style="cursor: pointer !important"
    onmouseover="this.style = 'background-color: #2185D0; color: white'; " 
    onmouseleave="this.style = 'background-color: none; color: #2185D0'; "
    href="{{ url_for('dashboard.submit_message', chat_id=chat.id, input='Dinner') }}">
    <p><b>4. Dinner</b> &ensp; <i class="Dinner send icon" ></i></p>
      <!-- All openning time -->
  </a>
  &ensp;
  <a class="ui primary icon circular label basic" 
    style="cursor: pointer !important"
    onmouseover="this.style = 'background-color: #2185D0; color: white'; " 
    onmouseleave="this.style = 'background-color: none; color: #2185D0'; "
    href="{{ url_for('dashboard.submit_message', chat_id=chat.id, input='Specific time') }}">
    <p><b>5. Specific time</b> &ensp; <i class="specific send icon" ></i></p>
    <!-- Choose opening time by myself -->
  </a>
  &ensp;
  <a class="ui primary icon circular label basic" 
    style="cursor: pointer !important"
    onmouseover="this.style = 'background-color: #2185D0; color: white'; " 
    onmouseleave="this.style = 'background-color: none; color: #2185D0'; "
    href="{{ url_for('dashboard.submit_message', chat_id=chat.id, input='Anytime') }}">
    <p><b>6. Anytime</b> &ensp; <i class="anytime send icon" ></i></p>
      <!-- All openning time -->
  </a>
  &ensp;
{% endmacro %}


{% macro Random() %}
  <!-- Quick Reply #Random -->
  <a class="ui black icon circular label basic" 
  onmouseover="this.style = 'background-color: black; color: white'; " 
  onmouseleave="this.style = 'background-color: none; color: black'; "
  onclick="randomSentence()">
  <p><b>Random Sentence</b> &ensp;<i class="dice five icon"></i></p>
  <!-- Start talk from beginning -->
  </a>
  &ensp;

  <script>
    function randomSentence() {
      fetch('{{ url_for("dashboard.random_sentence") }}')
        .then(response => response.text())
        .then(randValue => {
          $('#input')[0].value = randValue;
          $('#input')[0].focus()
        })
        .catch(error => {
          console.error('Error:', error);
        });
    }
  </script>
{% endmacro %}


{% macro Reset(chat) %}
  <!-- Quick Reply #Reset -->
  <a class="ui red icon circular label basic" 
  onmouseover="this.style = 'background-color: #9F3A38; color: white'; " 
  onmouseleave="this.style = 'background-color: none; color: #9F3A38'; " 
  href="{{ url_for('dashboard.submit_message', chat_id=chat.id, input='Reset') }}">
  <i class="sync icon" ></i> &ensp;<b>Reset</b>&ensp;
  <!-- Start talk from beginning -->
  </a>
  &ensp;
{% endmacro %}